export enum ActionType{
    SEARCH_REPOSITORIES = " SEARCH_REPOSITORIES ",
    SEARCH_REPOSITORIES_SUCCESS = "SEARCH_REPOSITORIES_SUCCESS",
    SEARCH_REPOSITORIES_FAILED = "SEARCH_REPOSITORIES_FAILED"
}